apiVersion: v1
kind: Service
metadata:
  namespace: chat-platform
  name: scylla-external
spec:
  ports:
  - port: 9042
    targetPort: 9042
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: chat-platform
  name: scylla-external
subsets:
- addresses:
  - ip: 10.10.20.100  # ← IP вашей ScyllaDB VM
  ports:
  - port: 9042